name: Docker Actions

on: [push]

jobs:
  list_images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: List Docker Images
      run: docker image ls

  another_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Execute Some Other Actions
      run: echo "This is another job"
